don't generate histograms.xml if it is not git checkout
dirmd doesn't work if workspace is not git checkout.
e.g.
 chromium_src.tools.metrics.histograms.expand_owners.Error: dirmd failed: "/tmp/chromium/src/third_party/depot_tools/dirmd read -form sparse /tmp/chromium/src /tmp/chromium/src/tools/metrics/histograms/metadata/actor": dir "/tmp/chromium/src" is not in a git repository

On Cog, we set gclient custom vars generate_location_tags to false,
so build/config/gclient_args.gni has "generate_location_tags = false".

But the reason we don't build histograms.xml is
that workspace is not git checkout,
so check .git existence, not generate_location_tags.

Bug: 329080012
Change-Id: I02c8752b26cb8bc23337324606d20083eaae682c
Reviewed-on: https://chromium-review.googlesource.com/c/chromium/src/+/7985206
Reviewed-by: Jesse McKenna <jessemckenna@google.com>
Auto-Submit: Fumitoshi Ukai <ukai@google.com>
Commit-Queue: Fumitoshi Ukai <ukai@google.com>
Cr-Commit-Position: refs/heads/main@{#1652987}