[PDF Ink Signatures] Move some commit tests to text_annotations_test
2 regression tests for bugs that were caused by incorrect timing
between initializing a new annotation and committing the previous
one are currently in the ink-text-box test suites. Responsibility for
this handoff is moving to ink-text-annotations in
https://crrev.com/c/7929152 so this CL moves the tests to the
ink-text-annotations suite to make it easier to verify that the tests
are not regressed when updating the production code.

The tests are kept almost entirely unchanged, with the following
exception: they are changed to initialize ink-text-annotations, the
parent of the ink-text-box, instead of only ink-text-box itself.

To allow the tests to pass without introducing a dependency on
setUpTextBoxTest from the ink-test-annotations suite, the
ink-text-annotations test setup is improved to reduce code
duplication and to set up the fake PdfViewerPrivateProxy.

Bug: 421421340
Change-Id: I7cbe829126e256f5f0153da6068acdcaacc5b417
Reviewed-on: https://chromium-review.googlesource.com/c/chromium/src/+/7934554
Reviewed-by: Andy Phan <andyphan@chromium.org>
Commit-Queue: Rebekah Potter <rbpotter@chromium.org>
Cr-Commit-Position: refs/heads/main@{#1649199}